ENV_AUDIO_DATA_BUCKET = "AUDIO_DATA_BUCKET"
ENV_AUDIO_METADATA_TABLE = "AUDIO_METADATA_TABLE"
ENV_RUNPOD_API_KEY_SECRET = "RUNPOD_API_KEY_SECRET"

AUDIO_METADATA_TABLE_NAME = "AudioMetadata"
AUDIO_DATA_BUCKET = "entropy-audio-data-us-east-1"